### ISSUE TITLE
Google code copy had version 1.29 - this seems to be 1.27

### ISSUE THREAD

**Issue by tillea** [lanzen/ampliconnoise#28]
Hi,
there exist lots of copies of old versions of ampliconnoise on Github. Version on (closed) googlecode was 1.29. What about ending the confusing for users and merge the different Github clones?
Please see also [disigma/ampliconnoise](https://github.com/disigma/ampliconnoise/issues/29)
Thanks for considering  Andreas.

**Comment by lanzen** [comment]
Hi,
My mistake - I naively used Google's migration tool to Github some 1.5 years ago when they were closing down assuming, but not checking (it seems), that the right version got exported. It seems to have done some weird things like creating two extra branches and migrating the wrong version. Sorry about that. I have now committed and pushed the latest v1.29 from my local files instead and made a proper clone and a release including compiled binaries. So everything should now be much more orderly. But please verify this as I am not using git very much and may have made some mistakes.

Cheers,
Anders

**Comment by tillea** [comment]
Hi Anders,

thanks for doing so.  I have informed those other clones you can find on
Github by doing a search for ampliconnoise and and hope that no other
forks that might confuse users will hang around.

I have added a comment to
  https://github.com/disigma/ampliconnoise/issues/29
  https://github.com/b4winckler/ampliconnoise/issues/1
  https://github.com/fhcrc/ampliconnoise/issues/4

I will point the homepage URL of the Debian package to your clone
since you was the first answering my bug report which I also filed
to the other clones

Thanks a lot for your quick response

```
 Andreas.
```

On Thu, Nov 17, 2016 at 01:16:58AM -0800, Anders Lanzen wrote:

> Hi,
> My mistake - I naively used Google's migration tool to Github some four years ago when they were closing down assuming but not check carefully enough that the right version got exported. It seems to have done some weird things like creating two extra branches and migrating the wrong version. Sorry about that. I have now committed and pushed the latest v1.29 from my local files instead and made a proper clone and a release including compiled binaries. So everything should now be much more orderly. But please verify this as I am not using git very much and may have made some mistakes.
> 
> Cheers,
> Anders
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lanzen/ampliconnoise/issues/28#issuecomment-261194727

## 

http://fam-tille.de
